LayoutViewExample/Models/ListModel.cs
namespace LayoutViewExample.Models
{
    public class ListModel
    {
        public string ListTitle { get; set; } = "";
        public List<string> ListItems { get; set; } = new List<string>();
    }
}

LayoutViewExample/Models/SalaryListModel.cs
namespace LayoutViewExample.Models
{
    public class SalaryListModel
    {
        public string ListTitle { get; set; } = "";
        public List<int> SalaryItems { get; set; } = new List<int>();
    }
}

LayoutViewExample/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using ServiceContracts;

namespace LayoutViewExample.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ICitiesService _cityService;
        private readonly ISalaryService _salaryService;
        private readonly IServiceScopeFactory _scopeFactory;

        //Constructor
        public EmployeeController(ICitiesService citiesService, ISalaryService salaryService, IServiceScopeFactory scopeFactory)
        {
            _cityService = citiesService;
            _salaryService = salaryService;
            _scopeFactory = scopeFactory;
            //object of Service classes 
            //_cityService = new CitiesService();
            //_salaryService = new SalaryService();
        }

        [Route("employee")]
        public IActionResult Index()
        {
            return View();
        }
      
        [Route("employee/emp-detail")]
        public IActionResult EmpDetails()
        {
            List<int> salaries = _salaryService.GetSalaries();
            ViewBag.Instance_SalaryId = _salaryService.GetId();
            return View(salaries);
        }

        [HttpGet("employee/dept-detail")]
        public IActionResult DeptDetails()
        {
            List<string> cities = _cityService.GetCities(); 

            using (IServiceScope scope = _scopeFactory.CreateScope())
            {
                scope.ServiceProvider.GetService<ISalaryService>();
            } // end of scope it calls dispose method 
            return View(cities);
        }
        [HttpPost("employee/dept-detail")]
        public IActionResult Dept()
        {
            List<string> cities = _cityService.GetCities();
            return View("DeptDetails", cities);
        }
    }
}

LayoutViewExample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using LayoutViewExample.Models;

namespace LayoutViewExample.Controllers
{
    public class HomeController : Controller
    {
        //for identifying environment variables 
        private readonly IWebHostEnvironment _webHostEnvironment;

        public HomeController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        [Route("/")]
        public ActionResult Index()
        {
            ViewBag.CurrentEnviornment = _webHostEnvironment.EnvironmentName;
            return View();
        }
        [Route("login")]

        public IActionResult Login()
        {
            ViewData["Title"] = "login";
            ViewBag.Title = "login";
            return View();
        }
        [Route("login")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login1()
        {
            return Json("true");
        }
        [Route("about")]
        public IActionResult About()
        {
            return View();
        }
        [Route("contact-us")]
        public IActionResult Contact()
        {
            return View();
        }
        [Route("contact-details")]
        public IActionResult ContactDetails()
        {
            ListModel listModel = new ListModel()
            {
                ListTitle = "Contact List",
                ListItems = new List<string>() {
                 "Phone No : 123435646",
                 "Email: abc@gmail.com ",
                 "address: gondal"
                 }
            };
            ViewData["Title"] = "Contact Us";
            return PartialView("_ListPartialView", listModel);
        }
    }
}

LayoutViewExample/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace LayoutViewExample.ViewComponents
{
    public class GridViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("Default");
        }
    }
}

LayoutViewExample/Views/Employee/DeptDetails.cshtml
@model IEnumerable<string>

@{
    ViewData["Title"] = "Employee-DepartmentDetails";

    var employees = new[]
    {
        new { Name = "John Doe", Department = "Human Resources", Position = "HR Manager" },
        new { Name = "Jane Smith", Department = "IT", Position = "Software Engineer" },
        new { Name = "Emily Johnson", Department = "Marketing", Position = "Marketing Specialist" }
    };
}

<!DOCTYPE html>
<html>
<head>
    <title>Department Details</title>
</head>
<body>
    <div class="employee-details">
        <h1>Employee Details</h1>
        @foreach (var emp in employees)
        {
            <div class="employee">
                <h2>@emp.Name</h2>
                <p><strong>Department:</strong> @emp.Department</p>
                <p><strong>Position:</strong> @emp.Position</p>
                <p></p>
            </div>
        }
        <h1>Cities</h1>
        <ul class="list">
            @foreach (string city in Model)
            {
                <li>@city</li>
            }
        </ul>
    </div>
</body>
</html>

LayoutViewExample/Views/Employee/EmpDetails.cshtml
@model IEnumerable<int>

@{
    ViewData["Title"] = "EmployeeDetail";
    var employees = new[]
    {
        new {
            Name = "John Doe",
            Department = "Human Resources",
            Position = "HR Manager",
            Email = "john.doe@example.com",
            Phone = "(123) 456-7890"
        },
        new {
            Name = "Jane Smith",
            Department = "Marketing",
            Position = "Marketing Director",
            Email = "jane.smith@example.com",
            Phone = "(456) 789-0123"
        },
        new {
            Name = "Michael Johnson",
            Department = "Finance",
            Position = "Financial Analyst",
            Email = "michael.johnson@example.com",
            Phone = "(789) 012-3456"
        }
    };
}

<!DOCTYPE html>
<html>
<head>
    <title>Employee Details</title>
</head>
<body>
    <h1>Employee Details</h1>

    <table class="table w-100 mt">
        <thead>
            <tr>

            </tr>
        </thead>
    </table>
    @foreach (var employee in employees)
    {
        <div>
            <p><strong>Name:</strong> @employee.Name</p>
            <p><strong>Department:</strong> @employee.Department</p>
            <p><strong>Position:</strong> @employee.Position</p>
            <p><strong>Email:</strong> @employee.Email</p>
            <p><strong>Phone:</strong> @employee.Phone</p>
            <p><strong>SalaryID:</strong>@ViewBag.Instance_SalaryId</p>
            <br />
            <hr /> 
        </div>
    }
    <h1>Salaries of employee are: </h1>
    <ul class="list">
        @foreach(int salary in Model)
        {
            <li>@salary</li>
        }
    </ul>
</body>
</html>

LayoutViewExample/Views/Employee/Index.cshtml
@{
    ViewData["Title"] = "Employee Home Page";
}
<h1>Welcome Employee </h1>
<p>home page for employee</p>

<div class="box">
    Environment: @ViewBag.CurrentEnviornment
</div>

LayoutViewExample/Views/Home/About.cshtml
@{
    @*Layout = "~/Views/Shared/_Layout.cshtml";*@ // imported from _ViewStart so no need to write 
    ViewData["Title"] = "About";
}

<!DOCTYPE html>
<html>
<head>
    <title>About</title>
    <link href="~/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <div class="about-container">
        <h1>Welcome to our ASP.NET application! </h1>
        
        <ul>
            <li>Secure user authentication and authorization</li>
            <li>Intuitive user interface with responsive design</li>
            <li>Advanced data management with SQL Server</li>
            <li>Real-time updates and notifications</li>
            <li>Comprehensive reporting and analytics</li>
        </ul>
        <p>
            Our team is dedicated to continuously improving the application by adding new features and enhancing existing ones based on user feedback. We strive to provide the best possible experience for our users.
        </p>
        <p>Thank you for choosing our ASP.NET application!</p>
    </div>
</body>
</html>

LayoutViewExample/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
}

<h1>Contact detail page</h1>
<p>Details regarding contact are here</p>
<button class="button button-blue-back" type="button" id="btn">Show Details</button>
<div class="box contact-list" id="name">

</div>
<script>
    document.querySelector("#btn").addEventListener("click",async function () {
        /*document.getElementById("name").innerHTML = 'devanshi';*/
        var response = await fetch("contact-details");
        var Details = await response.text();
        document.querySelector(".contact-list").innerHTML = Details;
    })
</script>

LayoutViewExample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
   
}

<h1>Welcome to home Page</h1>

@* Call for ViewComponent *@
@await Component.InvokeAsync("Grid")

<div class="box">
    Environment: @ViewBag.CurrentEnviornment
</div>

LayoutViewExample/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
    /* Layout = "~/Views/Shared/signIn.cshtml" */;
}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link href="~/loginStyles.css" rel="stylesheet" />
</head>
<body>
    <hr />
    <div>
        <h1>Login To Your Account!</h1>
        <div class="login-container">
            <form id="loginForm" action="Login" method="post" onsubmit="return validateForm()">
                @Html.AntiForgeryToken()
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" placeholder="Username" required><br>

                <label for="password">Password:</label>
                <input type="password" id="password" name="password" placeholder="Password" required>

                <input type="submit" value="Login">
            </form>
            <p id="errorMessage" class="error-message"></p>
            <div class="signup-link">
                <span>New User? <a href="@Url.Action("SignUp", "Account")">Sign Up</a></span><br><br>
                <a href="@Url.Action("ForgotPassword", "Account")">Forgot password</a>
            </div>
        </div>
    </div>
    
    <script src="~/script.js"></script>
</body>
</html>

LayoutViewExample/Views/Home/_ListPartialView.cshtml
@using LayoutViewExample.Models
@model ListModel

<div class="contact-list">
    <h3>@Model.ListTitle</h3>
    <ul class="list">
        @foreach (string item in Model.ListItems)
        {
            <li>@item</li>
        }
    </ul>
</div>

LayoutViewExample/Views/Shared/Components/Grid/Default.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>@ViewBag.Title</title>
</head>
<body>

<div class="box">
    <h2>Table</h2>
        <table class="table w-100">
            <tr>
                <td>Row 1, Col 1</td>
                <td>Row 1, Col 2</td>
                <td>Row 1, Col 3</td>
            </tr>
            <tr>
                <td>Row 2, Col 1</td>
                <td>Row 2, Col 2</td>
                <td>Row 2, Col 3</td>
            </tr>
            <tr>
                <td>Row 3, Col 1</td>
                <td>Row 3, Col 2</td>
                <td>Row 3, Col 3</td>
            </tr>
        </table>
    </div>

</body>
</html>

LayoutViewExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link href="~/StyleSheet.css" rel="stylesheet"/>
</head>
<body>
    <div class="container">
        <div class="navbar">
            <div class="navbar-brand">Asp.net Web App</div>
            <ul>
                <li><a href="/employee/emp-detail">EmplDetails</a></li>
                <li><a href="/employee/dept-detail">DeptDetails</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/contact-us">Contact-Us</a></li>
            </ul>
            <ul>
                <li><a href="/login">Login</a></li>
            </ul>
        </div>
        
        <div class="page-content">
            @RenderBody()
        </div>
    </div>
    <div>
       
    </div>
</body>
</html>

LayoutViewExample/Views/Shared/signIn.cshtml
@RenderBody()